#!/usr/bin/env bash

# Config.
COUNT=1 # Image count to fetch per source.
NSFW="all" # Include nsfw images or not. Valid values: true | false | both

USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"

# Source waifu.im.
# https://docs.waifu.im/docs/intro
WAIFUIM_URL="https://api.waifu.im/images"
curl -s "${WAIFUIM_URL}?pagesize=${COUNT}&isnsfw=${NSFW}" | jq -r '.items[].url'

# Source danbooru.
# https://danbooru.donmai.us/wiki_pages/help:api
DANBOORU_URL="https://danbooru.donmai.us/posts"
curl -s "${DANBOORU_URL}.json?limit=${COUNT}" | jq -r '.[] | .file_url'

# Source safebooru.
# https://safebooru.org/index.php?page=help&topic=dapi
SAFEBOORU_URL="https://safebooru.org/index.php"
# TODO: not random, make this random, same image over and over again
curl -s "${SAFEBOORU_URL}?page=dapi&s=post&q=index&json=1&limit=${COUNT}" | jq -r '.[] | .file_url'

# TODO: gelbooru

# Source konachan.com (NSFW version).
# https://konachan.com/help/api
KONACHAN_COM_URL="https://konachan.com/post.json"
# curl -s "${KONACHAN_COM_URL}?limit=${COUNT}"

# Source konachan.net (SFW version).
# https://konachan.net/help/api
KONACHAN_NET_URL="https://konachan.net/post.json"
# curl -s "${KONACHAN_NET_URL}?limit=${COUNT}"

# Source yande.re.
# https://yande.re/help/api
YANDERE_URL="https://yande.re/post.json"
curl -s "${YANDERE_URL}?limit=${COUNT}" | jq -r '.[] | .file_url'

# TODO: e-shuushuu

# Source zerochan.
# https://www.zerochan.net/api
ZEROCHAN_URL="https://www.zerochan.net/?json"
curl -s -H "User-Agent: $USER_AGENT" "${ZEROCHAN_URL}" | jq
